services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personality_analysis_app
    ports:
      - "11444:11441"
    volumes:
      - .:/app
#    depends_on:
#      - db
    environment:
#      - DATABASE_URL=postgresql://postgres:postgres@db:5432/personality_analysis
      - SECRET_KEY="your_secret_key"
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    # command: "sh -c 'while true; do ping host.docker.internal; sleep 5; done'"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      sam-network:

#  db:
#    image: postgres:15
#    container_name: personality_analysis_db
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: personality_analysis
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      sam-network:
#
#volumes:
#  postgres_data:

networks:
  sam-network:
